name: Upload DAGs to GCP Bucket

on:
  push:
    branches:
      - release/cloud-composer-prod

jobs:
  upload_dags:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Authenticate to Google Cloud
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v1'
        with:
          version: '>= 363.0.0'

      - name: Upload dags folder to GCS
        run: gsutil -m rsync -r -d dags/ gs://bucket-orchestrator-dev-dags-3/dags/